# This compose file is for local development ONLY.

version: "3.7"

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  hasura:
    image: hasura/graphql-engine:v1.2.0-beta.3
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_ADMIN_SECRET: hasura
    ports:
      - "8080:8080"
    depends_on:
      - postgres
