version: 2.1

orbs:
  node: circleci/node@5.0.2

commands:
  deploy-to-clever-cloud:
    parameters:
      app-id:
        type: string
      directory:
        type: string
    steps:
      - run:
          name: << parameters.name >>
          command: |
            git config --global user.email "dsi@zenika.com"
            git config --global user.name "Zenika"
            git init
            git add .
            git commit -m "deploy!"
            npm install --global clever-tools
            clever login --secret=$CLEVER_SECRET --token=$CLEVER_TOKEN
            clever link << parameters.app-id >>
            clever deploy --force
          working_directory: << parameters.directory >>

jobs:

  web-checks:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: web
      - run:
          command: npm run lint:strict
          working_directory: web
      - run:
          command: npm run prettier:check
          working_directory: web

  server-checks:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: server
      - run:
          command: npm run lint:strict
          working_directory: server
      - run:
          command: npm run prettier:check
          working_directory: server

  deploy:
    parameters:
      clever-app-id:
        type: string
      hasura-clever-app-id:
        type: string
      deploy-dir:
        type: string
        default: ../deploy
      hasura-deploy-dir:
        type: string
        default: ../hasura
      hasura-endpoint:
        type: string
      hasura-admin-secret:
        type: env_var_name
    executor: node/default
    steps:
      - checkout
      - run:
          name: Package Hasura
          command: |
            mkdir --parents << parameters.hasura-deploy-dir >>
            cp hasura/Dockerfile << parameters.hasura-deploy-dir >>/
      - deploy-to-clever-cloud:
          name: Deploy Hasura
          directory: << parameters.hasura-deploy-dir >>
          app-id: << parameters.hasura-clever-app-id >>
      - node/install-packages
      - run:
          name: Apply migrations and metadata
          command: |
            npm run hasura migrate apply -- --endpoint << parameters.hasura-endpoint >> --admin-secret ${<< parameters.hasura-admin-secret >>}
            npm run hasura metadata apply -- --endpoint << parameters.hasura-endpoint >> --admin-secret ${<< parameters.hasura-admin-secret >>}
      - attach_workspace:
          at: ./
      - run:
          name: Package
          command: |
            mkdir --parents << parameters.deploy-dir >>/public
            cp --recursive server/* << parameters.deploy-dir >>/
            cp --recursive web/dist/* << parameters.deploy-dir >>/public/
      - deploy-to-clever-cloud:
          name: Deploy App
          directory: << parameters.deploy-dir >>
          app-id: << parameters.clever-app-id >>

workflows:
  build:
    jobs:
      - web-checks
      - server-checks
      - node/run:
          name: web-build
          app-dir: web
          npm-run: build
          post-steps:
            - persist_to_workspace:
                root: ./
                paths: [web/dist/]
            - store_artifacts:
                path: web/dist
      - deploy:
          name: deploy-prod
          requires:
            - web-build
          filters:
            branches:
              only: upgrade_ci
          clever-app-id: app_8564d3e3-0694-4b87-a6e7-0000a633229b
          hasura-clever-app-id: app_6da7f582-6eda-4836-b716-fcaa8ddce036
          hasura-endpoint: https://hasura.links.zenika.com
          hasura-admin-secret: HASURA_ADMIN_SECRET
          context: clever-cloud2-zenika-dev
